FROM alpine:latest

RUN apk add --no-cache ca-certificates fuse3 sqlite

COPY --from=flyio/litefs:0.5 /usr/local/bin/litefs /usr/local/bin/litefs

COPY litefs.local.yml /etc/litefs.local.yml

ENV PATH="/usr/local/bin:${PATH}"

RUN mkdir -p /litefs

CMD sh -c "touch /litefs/halloween_stories.db && litefs mount -config /etc/litefs.local.yml"