version: '3.8'

services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    volumes:
      - litefs_data:/litefs
      - ./litefs.local.yml:/etc/litefs.local.yml
    environment:
      - FLY_REGION=local
      - PRIMARY_REGION=local
    privileged: true
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD-SHELL", "pgrep litefs || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - litefs_data:/litefs
    environment:
      - FLY_REGION=local
      - PRIMARY_REGION=local
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8081:8080"
    command: sh -c "echo 'Starting app service' && air -c .air.toml"

volumes:
  litefs_data: