FROM golang:1.21-alpine

WORKDIR /app

RUN apk add --no-cache gcc musl-dev

COPY go.mod go.sum ./
RUN go mod download
RUN go mod tidy

COPY . .

RUN go install github.com/cosmtrek/air@v1.49.0

CMD ["air", "-c", ".air.toml"]