app = "halloween-story-generator"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  PRIMARY_REGION = "iad"

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1

[[vm]]
  cpu_kind = "shared"
  cpus = 1
  memory_mb = 1024